emu:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60  
  q1_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 15.0, i: 6, d: 15}
  q2_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 300.0, i: 500, d: 9}
  q3_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 200.0, i: 180, d: 4}
  q4_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 6.0, i: 0.5, d: 3}
  q5_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 2.0, i: 0.5, d: 3}
  q6_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 0.075, i: 0, d: 0.05}
