emu:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60  
  qd1_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_1
    pid: {p: 15.0, i: 5, d: 0}
  qd2_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_2
    pid: {p: 200.0, i: 100, d: 0}
  qd3_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_3
    pid: {p: 100.0, i: 60, d: 0}
  qd4_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_4
    pid: {p: 12.0, i: 1, d: 0}
  qd5_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_5
    pid: {p: 9.0, i: 1, d: 0}
  qd6_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_6
    pid: {p: 0.2, i: 0.1, d: 0}
