controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_tool_controller
    joints:
      - sliding_jaw_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home_pose